<a href="https://colab.research.google.com/github/chornamarta/ml3.0/blob/main/Module%202/Linear%20Regression/HW_2_1_4_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
vector = np.random.rand(10)
vector

array([0.01734197, 0.03659865, 0.87642402, 0.93563733, 0.00891749,
       0.05189726, 0.13174782, 0.83727732, 0.61272322, 0.06329959])

In [5]:
vector.shape

(10,)

In [3]:
matrix = np.array([[11,14,17],
                   [20,23,26],
                   [29,32,35]])
matrix

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [6]:
matrix.shape

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [14]:
vector10 = np.round(vector,2) + 10
vector10

array([10.02, 10.04, 10.88, 10.94, 10.01, 10.05, 10.13, 10.84, 10.61,
       10.06])

In [15]:
matrix * 2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [17]:
vector_sqr = np.round(vector,2)**2
vector_sqr

array([4.000e-04, 1.600e-03, 7.744e-01, 8.836e-01, 1.000e-04, 2.500e-03,
       1.690e-02, 7.056e-01, 3.721e-01, 3.600e-03])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [18]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [19]:
result_matrix = np.dot(A,B)
result_matrix

array([[0.232 , 0.1627, 0.2145],
       [0.3061, 0.4867, 0.633 ],
       [0.1393, 0.2261, 0.294 ]])

різні розмірності не можна множити для 2 і 3 пункту

In [20]:
matr_vec = np.dot(result_matrix,C)
matr_vec

ValueError: shapes (3,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)

In [21]:
matr_matr = np.dot(result_matrix,D)

ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [22]:
result_matrix.T

array([[0.232 , 0.3061, 0.1393],
       [0.1627, 0.4867, 0.2261],
       [0.2145, 0.633 , 0.294 ]])

In [23]:
vector.T

array([0.01734197, 0.03659865, 0.87642402, 0.93563733, 0.00891749,
       0.05189726, 0.13174782, 0.83727732, 0.61272322, 0.06329959])

зміни нема, тому що тут 1 рядок нема на що змінювати

In [24]:
column_vector = np.expand_dims(vector,axis=1)
column_vector

array([[0.01734197],
       [0.03659865],
       [0.87642402],
       [0.93563733],
       [0.00891749],
       [0.05189726],
       [0.13174782],
       [0.83727732],
       [0.61272322],
       [0.06329959]])

тепер вектор має вигляд колонки, а не рядка

по суті це тепер 10 рядків

In [25]:
column_vector.T

array([[0.01734197, 0.03659865, 0.87642402, 0.93563733, 0.00891749,
        0.05189726, 0.13174782, 0.83727732, 0.61272322, 0.06329959]])

In [26]:
column_vector.T.shape

(1, 10)